version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - '2181:2181'
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - '9094:9094'
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL


  pyspark:
    image: jupyter/pyspark-notebook
    container_name: pyspark
    ports:
      - '8888:8888'
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3001:3000
    environment:
      - GF_INSTALL_PLUGINS=hamedkarbasi93-kafka-datasource

    